---
# tasks file for synclounge / docker

- name: Create and run SyncLounge container
  docker_container:
    name: "{{ synclounge_docker_name }}"
    image: "{{ synclounge_docker_image }}"
    ports:
      - "8088:8088"
      - "8089:8089"
    env:
      DOMAIN: "{{ synclounge_domain }}"
    restart_policy: always
    state: started
