---
# tasks file for synclounge / manual

- name: Install NodeJS
  apt:
    name: ['nodejs', 'npm']
    state: present
    update_cache: true

- name: Create SyncLounge group
  group:
    name: "{{ synclounge_group }}"
    state: present

- name: Create SyncLounge user
  user:
    name: "{{ synclounge_user }}"
    group: "{{ synclounge_group }}"
    home: "{{ synclounge_lib }}"
    create_home: false
    shell: /usr/sbin/nologin
    system: true
    state: present

- name: Clone SyncLounge git repository
  git:
    repo: "{{ synclounge_repo }}"
    dest: "{{ synclounge_lib }}"
    version: "{{ synclounge_version }}"
    force: true
  register: status_synclounge_git

#- meta: end_play

- name: Run npm install command
  command: /usr/bin/npm install
  args:
    chdir: "{{ synclounge_lib }}"
  retries: 3
  register: status_npm_install
  until: status_npm_install.rc == 0
  when: status_synclounge_git.changed

- name: Run npm run build command
  command: /usr/bin/npm run build
  args:
    chdir: "{{ synclounge_lib }}"
  retries: 3
  register: status_npm_build
  until: status_npm_build.rc == 0
  when: status_synclounge_git.changed

- name: Correct SyncLounge lib permissions
  file:
    path: "{{ synclounge_lib }}"
    owner: "{{ synclounge_user }}"
    group: "{{ synclounge_group }}"
    mode: '0775'
    recurse: true
    state: directory

- name: Configure SyncLounge services
  template:
    src: synclounge.service.j2
    dest: "/etc/systemd/system/synclounge-{{ item.name }}.service"
    owner: root
    group: root
    mode: '644'
  vars:
    synclounge_app_name: "{{ item.name }}"
    synclounge_app_command: "{{ item.command }}"
  with_items:
    - name: web
      command: /usr/bin/node webapp.js --accessUrl=http://{{ synclounge_domain }}
    - name: server
      command: /usr/bin/npm run server
  notify: restart synclounge-{{ item.name }}
  register: status_synclounge_systemd

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  changed_when: true
  when: status_synclounge_systemd.changed

- name: Start and enable SyncLounge services
  service:
    name: synclounge-{{ item }}
    state: started
    enabled: true
  with_items: ['web', 'server']
