---
# tasks file for plex / debian, ubuntu

- name: Configure Plex repository
  apt_repository:
    repo: "{{ plex_repo_url }}"
    state: present
    update_cache: false
  register: status_plex_repo

- name: Add Plex repository key
  apt_key:
    url: "{{ plex_repo_key }}"
    state: present
  register: status_plex_repo
