---
# tasks file for plex

- name: "Include {{ ansible_os_family }} specific vars"
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "{{ ansible_os_family }} derivatives setup tasks"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: "Install Plex Server"
  package:
    name: "{{ plex_package_name }}"
    state: "{{ plex_package_state }}"
    update_cache: "{{ status_plex_repo.changed }}"
  notify: "start and enable plex service"
