---
# tasks file for plex / redhat, centos

- name: Configure Plex repository
  yum_repository:
    name: PlexRepo
    baseurl: "{{ plex_repo_url }}"
    description: Plex Server Repo
    gpgcheck: true
  register: status_plex_repo
  when: plex_repo

- name: Add Plex repository key
  rpm_key:
    key: "{{ plex_repo_key }}"
    state: present
  register: status_plex_repo
  when: plex_repo
