---
# defaults file for traefik

traefik_user: "traefik"
traefik_group: "traefik"

traefik_domain_plex: "{{ plex_domain }}"
traefik_domain_synclounge: "{{ synclounge_domain }}"

traefik_version: "2.2.0"
traefik_download_url: "https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_v{{ traefik_version }}_linux_amd64.tar.gz"
traefik_download_tmp: "/tmp/traefik"

traefik_binary: "{{ traefik_binary_dir }}/traefik"
traefik_binary_dir: "/usr/local/bin"
traefik_config: "{{ traefik_config_dir }}/traefik.yaml"
traefik_config_dir: "/etc/traefik"
traefik_config_dynamic: "{{ traefik_config_dir }}/dynamic.yaml"

traefik_acme_dir: "{{ traefik_config_dir }}/acme"
traefik_acme_file: "{{ traefik_config_dir }}/acme.json"
traefik_acme_email: "plex@example.com"

traefik_log_file: "{{ traefik_log_dir }}/traefik.log"
traefik_log_dir: "/var/log/traefik"
traefik_log_level: "INFO"

traefik_api_insecure: false
traefik_api_dashboard: false
