---
# tasks file for docker

- name: Configure Docker APT repository
  apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    state: present
    update_cache: false
  register: status_docker_apt_repo

- name: Add Docker APT repository key
  apt_key:
    url: "{{ docker_apt_repo_key }}"
    state: present
  register: status_docker_apt_key

- name: Update APT repository after change
  apt:
    update_cache: true
  when: status_docker_apt_repo.changed
     or status_docker_apt_key.changed

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Make sure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Install Docker SDK
  pip:
    name: docker
    state: present
